import type { DrinkType } from "../types.js";

const drinkSeed = [
  ["Märzen Bier", 5.0, "beer"],
  ["Lager", 4.8, "beer"],
  ["Pils", 5.1, "beer"],
  ["Radler", 2.5, "beer"],
  ["Weizenbier", 5.4, "beer"],
  ["Starkbier", 7.5, "beer"],
  ["Cider", 4.5, "cider"],
  ["Hard Seltzer", 4.5, "ready_to_drink"],
  ["Weißwein", 12.5, "wine"],
  ["Rotwein", 13.5, "wine"],
  ["Rosé", 12.0, "wine"],
  ["Prosecco", 11.0, "sparkling"],
  ["Sekt", 12.0, "sparkling"],
  ["Champagner", 12.0, "sparkling"],
  ["Sangria", 8.0, "wine_mix"],
  ["Aperol Spritz", 8.0, "spritz"],
  ["Campari Spritz", 8.5, "spritz"],
  ["Campari Soda", 10.0, "spritz"],
  ["Hugo", 6.5, "spritz"],
  ["Lillet Wild Berry", 6.5, "spritz"],
  ["Bellini", 7.0, "cocktail"],
  ["Mimosa", 6.0, "cocktail"],
  ["Weißer Spritzer", 6.0, "wine_mix"],
  ["Mojito", 13.0, "cocktail"],
  ["Caipirinha", 20.0, "cocktail"],
  ["Cuba Libre", 12.0, "longdrink"],
  ["Dark and Stormy", 12.0, "longdrink"],
  ["Gin Tonic", 12.0, "longdrink"],
  ["Whiskey Cola", 12.0, "longdrink"],
  ["Vodka Lemon", 12.0, "longdrink"],
  ["Vodka Cranberry", 12.0, "longdrink"],
  ["Long Island Iced Tea", 22.0, "cocktail"],
  ["Espresso Martini", 18.0, "cocktail"],
  ["Pornstar Martini", 16.0, "cocktail"],
  ["Martini", 28.0, "cocktail"],
  ["Negroni", 24.0, "cocktail"],
  ["Margarita", 18.0, "cocktail"],
  ["Paloma", 12.0, "cocktail"],
  ["Moscow Mule", 12.0, "cocktail"],
  ["Cosmopolitan", 16.0, "cocktail"],
  ["Daiquiri", 18.0, "cocktail"],
  ["Piña Colada", 13.0, "cocktail"],
  ["Sex on the Beach", 12.0, "cocktail"],
  ["Mai Tai", 18.0, "cocktail"],
  ["Tequila Sunrise", 13.0, "cocktail"],
  ["Amaretto Sour", 14.0, "cocktail"],
  ["Whiskey Sour", 18.0, "cocktail"],
  ["White Russian", 16.0, "cocktail"],
  ["Bloody Mary", 10.0, "cocktail"],
  ["French 75", 14.0, "cocktail"],
  ["Vodka", 40.0, "spirit"],
  ["Gin", 40.0, "spirit"],
  ["Rum", 40.0, "spirit"],
  ["Tequila", 38.0, "spirit"],
  ["Whiskey", 40.0, "spirit"],
  ["Jägermeister", 35.0, "spirit"],
  ["Jägerbomb", 15.0, "shot_mix"],
  ["Fernet", 39.0, "spirit"],
  ["Ouzo", 38.0, "spirit"],
  ["Sambuca", 38.0, "spirit"],
  ["Limoncello", 30.0, "spirit"],
  ["Baileys", 17.0, "liqueur"],
  ["Malibu", 21.0, "liqueur"],
  ["Korn", 32.0, "spirit"],
  ["Shot Mix", 20.0, "shot_mix"],
  ["Energy Vodka Mix", 10.0, "ready_to_drink"],
  ["Flying Hirsch", 15.0, "shot_mix"],
  ["Helles Bier", 5.0, "beer"],
  ["Export Bier", 5.2, "beer"],
  ["Dunkles Bier", 5.0, "beer"],
  ["Schwarzbier", 4.9, "beer"],
  ["Kellerbier", 5.2, "beer"],
  ["Zwickl", 5.4, "beer"],
  ["Maibock", 7.0, "beer"],
  ["Doppelbock", 8.0, "beer"],
  ["IPA", 6.5, "beer"],
  ["Pale Ale", 5.5, "beer"],
  ["Stout", 5.0, "beer"],
  ["Porter", 5.5, "beer"],
  ["Guinness Draught", 4.2, "beer"],
  ["Corona Extra", 4.5, "beer"],
  ["Desperados", 5.9, "beer"],
  ["Gose", 4.5, "beer"],
  ["Berliner Weisse", 3.0, "beer"],
  ["Shandy", 2.5, "beer"],
  ["Apple Cider", 5.0, "cider"],
  ["Perry", 4.5, "cider"],
  ["Strongbow", 4.5, "cider"],
  ["Somersby Apple", 4.5, "cider"],
  ["Smirnoff Ice", 4.0, "ready_to_drink"],
  ["Bacardi Breezer", 4.0, "ready_to_drink"],
  ["White Claw", 4.5, "ready_to_drink"],
  ["Twisted Tea", 5.0, "ready_to_drink"],
  ["Mikes Hard Lemonade", 5.0, "ready_to_drink"],
  ["Gruner Veltliner", 12.5, "wine"],
  ["Riesling", 12.0, "wine"],
  ["Chardonnay", 13.5, "wine"],
  ["Sauvignon Blanc", 13.0, "wine"],
  ["Pinot Grigio", 12.5, "wine"],
  ["Zweigelt", 13.0, "wine"],
  ["Merlot", 14.0, "wine"],
  ["Cabernet Sauvignon", 14.0, "wine"],
  ["Pinot Noir", 13.5, "wine"],
  ["Chianti", 13.0, "wine"],
  ["Portwein", 20.0, "fortified_wine"],
  ["Sherry Fino", 15.0, "fortified_wine"],
  ["Sherry Cream", 17.5, "fortified_wine"],
  ["Madeira", 18.0, "fortified_wine"],
  ["Vermouth Rosso", 15.0, "fortified_wine"],
  ["Vermouth Dry", 18.0, "fortified_wine"],
  ["Asti Spumante", 7.5, "sparkling"],
  ["Cava", 11.5, "sparkling"],
  ["Cremant", 12.0, "sparkling"],
  ["Lambrusco", 8.0, "sparkling"],
  ["Limoncello Spritz", 7.5, "spritz"],
  ["Elderflower Spritz", 6.5, "spritz"],
  ["Sarti Spritz", 8.0, "spritz"],
  ["Americano", 16.0, "cocktail"],
  ["Boulevardier", 25.0, "cocktail"],
  ["Old Fashioned", 32.0, "cocktail"],
  ["Manhattan", 30.0, "cocktail"],
  ["Sazerac", 35.0, "cocktail"],
  ["Mint Julep", 30.0, "cocktail"],
  ["Tom Collins", 12.0, "cocktail"],
  ["Gin Fizz", 12.0, "cocktail"],
  ["Bramble", 15.0, "cocktail"],
  ["Aviation", 20.0, "cocktail"],
  ["Clover Club", 14.0, "cocktail"],
  ["Sidecar", 24.0, "cocktail"],
  ["Last Word", 25.0, "cocktail"],
  ["Penicillin", 18.0, "cocktail"],
  ["Aperol Sour", 14.0, "cocktail"],
  ["Pisco Sour", 18.0, "cocktail"],
  ["Rum Sour", 18.0, "cocktail"],
  ["Tommys Margarita", 20.0, "cocktail"],
  ["Frozen Margarita", 10.0, "cocktail"],
  ["Zombie", 24.0, "cocktail"],
  ["Hurricane", 18.0, "cocktail"],
  ["Blue Lagoon", 12.0, "cocktail"],
  ["Sea Breeze", 10.0, "cocktail"],
  ["Bay Breeze", 10.0, "cocktail"],
  ["Woo Woo", 12.0, "cocktail"],
  ["Screwdriver", 12.0, "cocktail"],
  ["Harvey Wallbanger", 14.0, "cocktail"],
  ["Black Russian", 25.0, "cocktail"],
  ["Mudslide", 13.0, "cocktail"],
  ["Grasshopper", 10.0, "cocktail"],
  ["Singapore Sling", 14.0, "cocktail"],
  ["Planters Punch", 14.0, "cocktail"],
  ["Rum Punch", 12.0, "cocktail"],
  ["Painkiller", 12.0, "cocktail"],
  ["El Diablo", 14.0, "cocktail"],
  ["Ranch Water", 10.0, "cocktail"],
  ["Michelada", 4.5, "cocktail"],
  ["Absinthe", 60.0, "spirit"],
  ["Grappa", 40.0, "spirit"],
  ["Pisco", 40.0, "spirit"],
  ["Mezcal", 40.0, "spirit"],
  ["Cachaca", 40.0, "spirit"],
  ["Brandy", 40.0, "spirit"],
  ["Cognac", 40.0, "spirit"],
  ["Bourbon", 40.0, "spirit"],
  ["Scotch Whisky", 40.0, "spirit"],
  ["Irish Whiskey", 40.0, "spirit"],
  ["Rye Whiskey", 45.0, "spirit"],
  ["Marillen Schnaps", 40.0, "spirit"],
  ["Obstler", 40.0, "spirit"],
] as const;

export const fallbackDrinkTypes: DrinkType[] = drinkSeed.map(
  ([name, abvPercent, category], index) => ({
    abvPercent,
    category,
    id: `seed-${index + 1}`,
    isActive: true,
    name,
  }),
);
