import type { DrinkType } from "../types.js";

const drinkSeed = [
  ["Märzen Bier", 5.0, "beer"],
  ["Lager", 4.8, "beer"],
  ["Pils", 5.1, "beer"],
  ["Radler", 2.5, "beer"],
  ["Weizenbier", 5.4, "beer"],
  ["Starkbier", 7.5, "beer"],
  ["Cider", 4.5, "cider"],
  ["Hard Seltzer", 4.5, "ready_to_drink"],
  ["Weißwein", 12.5, "wine"],
  ["Rotwein", 13.5, "wine"],
  ["Rosé", 12.0, "wine"],
  ["Prosecco", 11.0, "sparkling"],
  ["Sekt", 12.0, "sparkling"],
  ["Champagner", 12.0, "sparkling"],
  ["Sangria", 8.0, "wine_mix"],
  ["Aperol Spritz", 8.0, "spritz"],
  ["Campari Spritz", 8.5, "spritz"],
  ["Campari Soda", 10.0, "spritz"],
  ["Hugo", 6.5, "spritz"],
  ["Lillet Wild Berry", 6.5, "spritz"],
  ["Bellini", 7.0, "cocktail"],
  ["Mimosa", 6.0, "cocktail"],
  ["Weißer Spritzer", 6.0, "wine_mix"],
  ["Mojito", 13.0, "cocktail"],
  ["Caipirinha", 20.0, "cocktail"],
  ["Cuba Libre", 12.0, "longdrink"],
  ["Dark and Stormy", 12.0, "longdrink"],
  ["Gin Tonic", 12.0, "longdrink"],
  ["Whiskey Cola", 12.0, "longdrink"],
  ["Vodka Lemon", 12.0, "longdrink"],
  ["Vodka Cranberry", 12.0, "longdrink"],
  ["Long Island Iced Tea", 22.0, "cocktail"],
  ["Espresso Martini", 18.0, "cocktail"],
  ["Pornstar Martini", 16.0, "cocktail"],
  ["Martini", 28.0, "cocktail"],
  ["Negroni", 24.0, "cocktail"],
  ["Margarita", 18.0, "cocktail"],
  ["Paloma", 12.0, "cocktail"],
  ["Moscow Mule", 12.0, "cocktail"],
  ["Cosmopolitan", 16.0, "cocktail"],
  ["Daiquiri", 18.0, "cocktail"],
  ["Piña Colada", 13.0, "cocktail"],
  ["Sex on the Beach", 12.0, "cocktail"],
  ["Mai Tai", 18.0, "cocktail"],
  ["Tequila Sunrise", 13.0, "cocktail"],
  ["Amaretto Sour", 14.0, "cocktail"],
  ["Whiskey Sour", 18.0, "cocktail"],
  ["White Russian", 16.0, "cocktail"],
  ["Bloody Mary", 10.0, "cocktail"],
  ["French 75", 14.0, "cocktail"],
  ["Vodka", 40.0, "spirit"],
  ["Gin", 40.0, "spirit"],
  ["Rum", 40.0, "spirit"],
  ["Tequila", 38.0, "spirit"],
  ["Whiskey", 40.0, "spirit"],
  ["Jägermeister", 35.0, "spirit"],
  ["Jägerbomb", 15.0, "shot_mix"],
  ["Fernet", 39.0, "spirit"],
  ["Ouzo", 38.0, "spirit"],
  ["Sambuca", 38.0, "spirit"],
  ["Limoncello", 30.0, "spirit"],
  ["Baileys", 17.0, "liqueur"],
  ["Malibu", 21.0, "liqueur"],
  ["Korn", 32.0, "spirit"],
  ["Shot Mix", 20.0, "shot_mix"],
  ["Energy Vodka Mix", 10.0, "ready_to_drink"],
  ["Flying Hirsch", 15.0, "shot_mix"],
] as const;

export const fallbackDrinkTypes: DrinkType[] = drinkSeed.map(
  ([name, abvPercent, category], index) => ({
    abvPercent,
    category,
    id: `seed-${index + 1}`,
    isActive: true,
    name,
  }),
);
