insert into public.drink_types (name, abv_percent, category)
values
  ('Helles Bier', 5.0, 'beer'),
  ('Export Bier', 5.2, 'beer'),
  ('Dunkles Bier', 5.0, 'beer'),
  ('Schwarzbier', 4.9, 'beer'),
  ('Kellerbier', 5.2, 'beer'),
  ('Zwickl', 5.4, 'beer'),
  ('Maibock', 7.0, 'beer'),
  ('Doppelbock', 8.0, 'beer'),
  ('IPA', 6.5, 'beer'),
  ('Pale Ale', 5.5, 'beer'),
  ('Stout', 5.0, 'beer'),
  ('Porter', 5.5, 'beer'),
  ('Guinness Draught', 4.2, 'beer'),
  ('Corona Extra', 4.5, 'beer'),
  ('Desperados', 5.9, 'beer'),
  ('Gose', 4.5, 'beer'),
  ('Berliner Weisse', 3.0, 'beer'),
  ('Shandy', 2.5, 'beer'),
  ('Apple Cider', 5.0, 'cider'),
  ('Perry', 4.5, 'cider'),
  ('Strongbow', 4.5, 'cider'),
  ('Somersby Apple', 4.5, 'cider'),
  ('Smirnoff Ice', 4.0, 'ready_to_drink'),
  ('Bacardi Breezer', 4.0, 'ready_to_drink'),
  ('White Claw', 4.5, 'ready_to_drink'),
  ('Twisted Tea', 5.0, 'ready_to_drink'),
  ('Mikes Hard Lemonade', 5.0, 'ready_to_drink'),
  ('Gruner Veltliner', 12.5, 'wine'),
  ('Riesling', 12.0, 'wine'),
  ('Chardonnay', 13.5, 'wine'),
  ('Sauvignon Blanc', 13.0, 'wine'),
  ('Pinot Grigio', 12.5, 'wine'),
  ('Zweigelt', 13.0, 'wine'),
  ('Merlot', 14.0, 'wine'),
  ('Cabernet Sauvignon', 14.0, 'wine'),
  ('Pinot Noir', 13.5, 'wine'),
  ('Chianti', 13.0, 'wine'),
  ('Portwein', 20.0, 'fortified_wine'),
  ('Sherry Fino', 15.0, 'fortified_wine'),
  ('Sherry Cream', 17.5, 'fortified_wine'),
  ('Madeira', 18.0, 'fortified_wine'),
  ('Vermouth Rosso', 15.0, 'fortified_wine'),
  ('Vermouth Dry', 18.0, 'fortified_wine'),
  ('Asti Spumante', 7.5, 'sparkling'),
  ('Cava', 11.5, 'sparkling'),
  ('Cremant', 12.0, 'sparkling'),
  ('Lambrusco', 8.0, 'sparkling'),
  ('Limoncello Spritz', 7.5, 'spritz'),
  ('Elderflower Spritz', 6.5, 'spritz'),
  ('Sarti Spritz', 8.0, 'spritz'),
  ('Americano', 16.0, 'cocktail'),
  ('Boulevardier', 25.0, 'cocktail'),
  ('Old Fashioned', 32.0, 'cocktail'),
  ('Manhattan', 30.0, 'cocktail'),
  ('Sazerac', 35.0, 'cocktail'),
  ('Mint Julep', 30.0, 'cocktail'),
  ('Tom Collins', 12.0, 'cocktail'),
  ('Gin Fizz', 12.0, 'cocktail'),
  ('Bramble', 15.0, 'cocktail'),
  ('Aviation', 20.0, 'cocktail'),
  ('Clover Club', 14.0, 'cocktail'),
  ('Sidecar', 24.0, 'cocktail'),
  ('Last Word', 25.0, 'cocktail'),
  ('Penicillin', 18.0, 'cocktail'),
  ('Aperol Sour', 14.0, 'cocktail'),
  ('Pisco Sour', 18.0, 'cocktail'),
  ('Rum Sour', 18.0, 'cocktail'),
  ('Tommys Margarita', 20.0, 'cocktail'),
  ('Frozen Margarita', 10.0, 'cocktail'),
  ('Zombie', 24.0, 'cocktail'),
  ('Hurricane', 18.0, 'cocktail'),
  ('Blue Lagoon', 12.0, 'cocktail'),
  ('Sea Breeze', 10.0, 'cocktail'),
  ('Bay Breeze', 10.0, 'cocktail'),
  ('Woo Woo', 12.0, 'cocktail'),
  ('Screwdriver', 12.0, 'cocktail'),
  ('Harvey Wallbanger', 14.0, 'cocktail'),
  ('Black Russian', 25.0, 'cocktail'),
  ('Mudslide', 13.0, 'cocktail'),
  ('Grasshopper', 10.0, 'cocktail'),
  ('Singapore Sling', 14.0, 'cocktail'),
  ('Planters Punch', 14.0, 'cocktail'),
  ('Rum Punch', 12.0, 'cocktail'),
  ('Painkiller', 12.0, 'cocktail'),
  ('El Diablo', 14.0, 'cocktail'),
  ('Ranch Water', 10.0, 'cocktail'),
  ('Michelada', 4.5, 'cocktail'),
  ('Absinthe', 60.0, 'spirit'),
  ('Grappa', 40.0, 'spirit'),
  ('Pisco', 40.0, 'spirit'),
  ('Mezcal', 40.0, 'spirit'),
  ('Cachaca', 40.0, 'spirit'),
  ('Brandy', 40.0, 'spirit'),
  ('Cognac', 40.0, 'spirit'),
  ('Bourbon', 40.0, 'spirit'),
  ('Scotch Whisky', 40.0, 'spirit'),
  ('Irish Whiskey', 40.0, 'spirit'),
  ('Rye Whiskey', 45.0, 'spirit'),
  ('Marillen Schnaps', 40.0, 'spirit'),
  ('Obstler', 40.0, 'spirit')
on conflict (name) do update
set abv_percent = excluded.abv_percent,
    category = excluded.category,
    is_active = true;
